# jeg vil ikke ha hjelp fra pus
# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/pus/forenklet-deploy
team: pus
webproxy: true
replicas:
  min: 1
  max: 1
  cpuThresholdPercentage: 50
port: 8800
healthcheck:
  liveness:
    path: internal/isAlive
    initialDelay: 60
  readiness:
    path: internal/isAlive
    initialDelay: 60
resources:
    requests: # Ressursene applikasjonen blir instansiert med
        cpu: 800m
        memory: 1024Mi
    limits:
        cpu: 2000m # Hvis applikasjonen overgår denne grensen vil cpu tilgangen bli kvalt.
        memory: 1536Mi # Overgår den derimot minne grensen vil den bli slettet ummidelbart.
fasitResources:
  used:
  - alias: unleash-api
    resourceType: restservice
  - alias: pus-github
    resourceType: applicationProperties
