version: 2.1
orbs:
  pus: navikt/pus-orb@0.0.2

jobs:
  deploy-forenklet-deploy:
    executor: pus/pus-pipeline
    steps:
      - pus/bygg-frontend
      - pus/bygg-backend
      - pus/bygg-og-push-docker-image
      - run: node /update-iac.js $VERSION default

workflows:
  version: 2
  commit:
    jobs:
      - pus/test-backend:
          context: pus
          filters:
            branches:
              ignore: master
      - pus/test-frontend:
          context: pus
          filters:
            branches:
              ignore: master
      - deploy-forenklet-deploy:
          context: pus
          filters:
            branches:
              only: master

