version: 2.1
orbs:
  pus:
    executors:

      pus-pipeline:
        docker:
          - image: navikt/pus-pipeline

    commands:

      oppdater_mvn_cache:
        steps:
          - run:
              name: Last ned settings.xml
              command: |
                curl -o settings.xml -L -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" "api.github.com/repos/navikt/pus-pipeline/contents/settings.xml"
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "settings.xml" }}
          - run: mvn -B -s settings.xml dependency:go-offline
          - save_cache:
              paths:
                - ~/.m2
              key: v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "settings.xml" }}

      oppdater_npm_cache:
        steps:
          - restore_cache:
              key: npm-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - run: npm ci
          - save_cache:
              key: npm-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
              paths:
                - /root/.npm

      bygg_og_push_docker_image:
        parameters:
          image_tag:
            type: string
        steps:
          - run:
              name: Bygg docker image
              command: |
                docker build -t navikt/$CIRCLE_PROJECT_REPONAME .
                docker tag navikt/$CIRCLE_PROJECT_REPONAME navikt/$CIRCLE_PROJECT_REPONAME:<<parameters.image_tag>>
          - run:
              name: Push docker image
              command: |
                echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
                docker push navikt/$CIRCLE_PROJECT_REPONAME
                echo "Pushet versjon <<parameters.image_tag>> av $CIRCLE_PROJECT_REPONAME"
                echo "https://cloud.docker.com/u/navikt/repository/docker/navikt/$CIRCLE_PROJECT_REPONAME"

      sett_versjon_og_tag_repo:
        steps:
          - run:
              name: Sett versjon
              command: echo "export VERSION=$(git rev-list --count HEAD).$(date +'%Y%m%d.%H%M')" >> $BASH_ENV
          - run:
              name: Tag git repo
              command: node /tag-repo.js $CIRCLE_PROJECT_REPONAME $VERSION

      oppdater_iac_repo:
        parameters:
          version:
            type: string
        steps:
          - run:
              name: Oppdater pto-iac
              command: node /update-iac.js <<parameters.version>>

      bygg-frontend:
        steps:
            - checkout
            - oppdater_npm_cache
            - run: npm run lint
            - run: npm run test
            - run: npm run build

      bygg-backend:
        steps:
          - checkout
          - oppdater_mvn_cache
          - run: mvn -B -s settings.xml package
          - store_test_results:
              path: target/surefire-reports

      deploy-backend:
        steps:
          - checkout
          - setup_remote_docker
          - add_ssh_keys
          - bygg-backend
          - sett_versjon_og_tag_repo
          - bygg_og_push_docker_image:
              image_tag: $VERSION
          - oppdater_iac_repo:
              version: $VERSION

    jobs:

      test-backend:
        executor: pus-pipeline
        steps:
          - checkout
          - oppdater_mvn_cache
          - run: mvn -B verify
          - store_test_results:
              path: target/surefire-reports

      test-frontend:
        executor: pus-pipeline
        steps:
          - checkout
          - oppdater_npm_cache
          - run: npm run lint
          - run: npm run test

      deploy-backend:
        executor: pus-pipeline
        steps:
          - deploy-backend


      deploy-frontend:
        executor: pus-pipeline
        steps:
          - checkout
          - setup_remote_docker
          - add_ssh_keys
          - bygg-frontend
          - sett_versjon_og_tag_repo
          - bygg_og_push_docker_image:
              image_tag: $VERSION
          - oppdater_iac_repo:
              version: $VERSION

      deploy-frontend-med-backend:
        executor: pus-pipeline
        steps:
          - bygg-frontend
          - deploy-backend


workflows:
  version: 2
  commit:
    jobs:
      - pus/test-backend:
          context: pus
          filters:
            branches:
              ignore: master
      - pus/test-frontend:
          context: pus
          filters:
            branches:
              ignore: master
      - pus/deploy-frontend-med-backend:
          context: pus
          filters:
            branches:
              only: master

