version: 2.1
orbs:
  pus: navikt/pus-orb@0.0.16

workflows:
  version: 2
  commit:
    jobs:
      - pus/test-backend:
          context: pus
          filters:
            branches:
              ignore: master
      - pus/test-frontend:
          context: pus
          filters:
            branches:
              ignore: master
      - pus/deploy-backend-med-frontend:
          cluster: dev-sbs
          filepath: ./nais.yaml
          configrepo: pto-config
          context: pus
          filters:
            branches:
              only: master
