version: 2.1
orbs:
  pus:
    executors:

      pus-pipeline:
        docker:
          - image: navikt/pus-pipeline

    commands:

      check_mvn_cache:
        steps:
          - run:
              name: Last ned settings.xml
              command: |
                curl -o settings.xml -L -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" "api.github.com/repos/navikt/pus-pipeline/contents/settings.xml"
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "settings.xml" }}
          - run: mvn -B -q -s settings.xml dependency:go-offline
          - save_cache:
              paths:
                - ~/.m2
              key: v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "settings.xml" }}

      check_npm_cache:
        parameters:
          package_lock_path:
            type: string
            default: package-lock.json
        steps:
          - restore_cache:
              key: npm-v1-{{ .Branch }}-{{ checksum "/root/project/<<parameters.package_lock_path>>" }}
          - run: npm ci
          - save_cache:
              key: npm-v1-{{ .Branch }}-{{ checksum "/root/project/<<parameters.package_lock_path>>" }}
              paths:
                - /root/.npm

      build_and_push_docker_image:
        parameters:
          image_tag:
            type: string
        steps:
          - run:
              name: Bygg docker image
              command: |
                docker build -t navikt/$CIRCLE_PROJECT_REPONAME .
                docker tag navikt/$CIRCLE_PROJECT_REPONAME navikt/$CIRCLE_PROJECT_REPONAME:<<parameters.image_tag>>
          - run:
              name: Push docker image
              command: |
                echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
                docker push navikt/$CIRCLE_PROJECT_REPONAME
                echo "Pushet versjon <<parameters.docker_image_tag>> av $CIRCLE_PROJECT_REPONAME"
                echo "https://cloud.docker.com/u/navikt/repository/docker/navikt/$CIRCLE_PROJECT_REPONAME"

    jobs:

      test-backend:
        executor: pus-pipeline
        steps:
          - checkout
          - check_mvn_cache
          - run: mvn -q -B verify
          - store_test_results:
              path: target/surefire-reports

      test-frontend:
        parameters:
          package_lock_path:
            type: string
            default: package-lock.json
        executor: pus-pipeline
        steps:
          - checkout
          - check_npm_cache:
              package_lock_path: <<parameters.package_lock_path>>
          - run: npm run test
          - run:
              name: Install JUnit coverage reporter
              command: npm i jest-junit
          - run:
              name: Create jest.config.js
              command: |
                echo '{ reporters: ["default", "jest-junit"] }' > jest.config.js
          - run:
              name: Run tests with JUnit as reporter
              command: jest --ci --runInBand --reporters=default --reporters=jest-junit
              environment:
                JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
          - store_test_results:
              path: reports/junit
          - store_artifacts:
              path: reports/junit

      deploy-backend:
        executor: pus-pipeline
        steps:
          - checkout
          - setup_remote_docker
          - add_ssh_keys
          - check_mvn_cache
          - run: mvn -B -q -s settings.xml package -B -q
          - store_test_results:
              path: target/surefire-reports
          - run:
              name: Sett versjon
              command: echo "export VERSION=$(git rev-list --count HEAD).$(date +'%Y%m%d.%H%M')" >> $BASH_ENV
          - run:
              name: Tag git repo
              command: node /tag-repo.js $CIRCLE_PROJECT_REPONAME $VERSION
          - build_and_push_docker_image:
              image_tag: $VERSION
          - run:
              name: Oppdater pto-iac
              command: node /update-iac.js $VERSION

workflows:
  version: 2
  commit:
    jobs:
      - pus/test-backend:
          context: pus
      - pus/test-frontend:
          context: pus
          package_lock_path: /src/frontend/package-lock.json

